#!/usr/bin/env python3
"""
    Module to read a WWB Report CSV
"""

import argparse
from pprint import pprint
from WWBLexer.WWBLexer import WWBLexer
import json

import datetime


wwb_lexer = WWBLexer()

parser = argparse.ArgumentParser(
                    prog = 'WWB Report generator',
                    description = 'Reads the CSV generated by WWB and outputs a file based on a template')

parser.add_argument('filenames', type=str, nargs='+',
                    help='Files to be scanned and generated')

def main():
    args = parser.parse_args()

    for file in args.filenames:
        #print(f"Reading file: {file}")

        with open(file, "r") as file: 
            report_str: str = file.read()#.replace(", ", ";")
            #print(report_str)

            #lexed_file = wwb_lexer.get_tokens_unprocessed(report_str)

            
            tree = wwb_lexer.get_wwb_tree(report_str, True)#wwb_lexer.wwb_tree
            print(wwb_lexer)
            #print(tree)
            #pprint(tree)
            #print(json.dumps(tree, indent=4))



if __name__ == '__main__':
    main()
    