#!/bin/bash

echo "Regenerating all testfiles"

for f in ./*.csv
do
    echo "Processing $f file..."
    # take action on each file. $f store current file name
    for format in md json
    do 
        ../GenReport.py -f $format $f > ./$format/${f%.csv}.$format
    done
done